<a href="https://colab.research.google.com/github/Queila-Cruz/Analise-lunar/blob/analise-resultados/Analise_Lunar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/Queila-Cruz/Analise-lunar.git

Cloning into 'Analise-lunar'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), 10.24 KiB | 5.12 MiB/s, done.

In [6]:
import pandas as pd

df_lua = pd.read_csv('/content/Analise-lunar/Moonlanding.csv')

display(df_lua)

,Mission,Spacecraft,Launch Date,Carrier Rocket,Operator,Mission Type,Outcome,Additional Information
0,Pioneer 0 (Able I),Pioneer 0,17-Aug-58,Thor DM-18 Able I,United States USAF,Orbiter,Launch failure,First attempted launch beyond Earth orbit; fai...
1,Luna E-1 No.1,Luna E-1 No.1,23-Sep-58,Luna,Soviet Union OKB-1,Impactor,Launch failure,Failed to orbit; rocket disintegrated due to e...
2,Pioneer 1 (Able II),Pioneer 1,11-Oct-58,Thor DM-18 Able I,United States NASA,Orbiter,Launch failure,Failed to orbit; premature second-stage cutoff...
3,Luna E-1 No.2,Luna E-1 No.2,11-Oct-58,Luna,Soviet Union OKB-1,Impactor,Launch failure,Failed to orbit; carrier rocket exploded due t...
4,Pioneer 2 (Able III),Pioneer 2,08-Nov-58,Thor DM-18 Able I,United States NASA,Orbiter,Launch failure,Failed to orbit; premature second-stage cutoff...
...,...,...,...,...,...,...,...,...
161,Peregrine Mission One,Peregrine,08-Jan-24,Vulcan Centaur VC2,Astrobotic Technology,Lander,Spacecraft failure,Part of CLPS. Peregrine lander's reaction thru...
162,Peregrine Mission One,Colmena ? 5,08-Jan-24,Vulcan Centaur VC2,UNAM,Rovers,Precluded,Part of CLPS. Peregrine lander's reaction thru...
163,Peregrine Mission One,Iris,08-Jan-24,Vulcan Centaur VC2,CMU,Rover,Precluded,Part of CLPS. Peregrine lander's reaction thru...
164,IM-1,Nova-C Odysseus,14-Feb-24,Falcon 9 B5,Intuitive Machines,Lander,Operational,First Nova-C mission. Payloads successfully de...
165,IM-1,EagleCam,14-Feb-24,Falcon 9 B5,ERAU,Deployable camera (semi hard lander),Awaiting Deployment,First Nova-C mission. Payloads successfully de...

In [19]:
# Análise 1 - Quantidade de Sucesso, falhas, etc.

display(df_lua['Outcome'].value_counts())

Outcome
Successful              78
Launch failure          31
Spacecraft failure      29
Operational             14
Partial failure          6
Operational              3
Precluded                2
En route                 1
Partial success          1
Awaiting Deployment      1
Name: count, dtype: int64

In [21]:
# Análise 2 - Somatório de registros da base de dados

display(len(df_lua))

166